In [1]:
import numpy as np
from scipy.linalg import solve

A = np.array([[3,2],[2,-1]])
B = np.array([[12],[1]])

x=solve(A,B)
print(x)
print(A.dot(x) - B)

[[2.]
 [3.]]
[[ 0.0000000e+00]
 [-8.8817842e-16]]


In [3]:
A = np.array([[4,-2],[6,1]])
b = np.array([[22],[45]])
x = solve(A,b)
print(x)

[[7.]
 [3.]]


In [8]:
import numpy as np
from scipy.optimize import linprog
c = np.array([-1,4])
A_ub = np.array([[-3,1],[1,2]])
b_ub = np.array([6,4])

x0_bounds = (None,None)
x1_bounds = (-3, None)

bounds = [x0_bounds,x1_bounds]
result = linprog(c,A_ub=A_ub,b_ub=b_ub,bounds=bounds)
print(result.message)
print(result.x)
print(result.fun)

Optimization terminated successfully. (HiGHS Status 7: Optimal)
[10. -3.]
-22.0


In [10]:
c = np.array([-4,-5,-4])
A_ub = np.array([[2,3,6],[4,2,4],[4,6,8]])
b_ub = np.array([240,200,160])


x1_bounds = (0,None)
x2_bounds = (0,None)
x3_bounds = (0,None)
bounds = [x1_bounds,x2_bounds,x3_bounds]
result = linprog(c,A_ub=A_ub,b_ub=b_ub,bounds=bounds)
print(result.message)
print(result.x)
print(result.fun)

Optimization terminated successfully. (HiGHS Status 7: Optimal)
[40.  0.  0.]
-160.0


In [4]:
import numpy as np
from scipy.linalg import solve
A = np.array([[3,1],[2,1]])
B = np.array([[-1],[0]])

x=solve(A,B)
print(x)
print(A.dot(x) - B)

[[-1.]
 [ 2.]]
[[-2.22044605e-16]
 [-2.22044605e-16]]


In [13]:
import numpy as np
from scipy.optimize import linprog
c = np.array([30,60])
A_ub = np.array([[1,3],[3,2]])
b_ub = np.array([21,21])
A_eq = np.array([[3,1]])
b_eq = np.array([18])

x1_bounds = (0,None)
x2_bounds = (0,None)

bounds = [x1_bounds,x2_bounds]
result = linprog(c,A_ub=A_ub,b_ub=b_ub,A_eq=A_eq,b_eq=b_eq,bounds=bounds)
print(result.message)
print(result.x)
print(result.fun)

Optimization terminated successfully. (HiGHS Status 7: Optimal)
[6. 0.]
180.0
